In [ ]:
import pandas as pd 
df = pd.read_csv('movies_data.csv', usecols= ['imdb_id', 'original_title', 'overview', '_id'])
print(len(df['_id'].values))
# a = "purple is the best city in the forst. That's really great at some great extent. But who do you know python?"
# b = "there is an art to getting your way and throwng banans on the the street is not it"
# c = "it is not often you find soggy banans on the street"
# d = "green should have smelled more tranquil but somewhoe it just tated rotten"
# e = "How to go to eagypt? to get your way you must not bombard the road with yellow fruit"
# docs = {"1": a, "2": b, "3": c, "4": d, "5": e}

# print(list(docs.values()))


5143


In [12]:
!pip install sentence-transformers faiss-cpu torch #faiss-cpu --no-cache

In [ ]:
x = 5
movies = (df['original_title'] + ". "+  df['overview']).to_list()

In [13]:
# transform docs 
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

import numpy as np 
import torch 

if not torch.cuda.is_available():
    print("Warning: No GPU found. Please add GPU to your notebook")


model = SentenceTransformer('msmarco-distilbert-base-v4')

if torch.cuda.is_available():
  model = model.to(torch.device("cuda"))
  print(model.device)
        
sentence_embeddings = model.encode(movies, show_progress_bar=True)
print(sentence_embeddings.shape)
        




  






    




ValueError: ignored

In [ ]:
pip uninstall sentence_transformers

Found existing installation: sentence-transformers 2.2.0


In [ ]:
from sentence_transformers import util
def ConsieSimilaritySearch():
  util

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
import pickle

with open('mcroembeddings.pkl', "rb") as fIn:
    sentence_embeddings = pickle.load(fIn)
    print("loadaed")
  

#sentence_embeddings

loadaed


In [ ]:
print(sentence_embeddings.shape)

(5143, 768)


In [ ]:

import faiss 
# at first approximation, this fraction is nprobe/nlist
d = sentence_embeddings[1]
def FaissIV():
    
    nlist = 15 # num of cells you want in your vironar
    d = sentence_embeddings.shape[1]
    quantizer = faiss.IndexFlatL2(d)
    index = faiss.IndexIVFFlat(quantizer, d, nlist)
    index.train(sentence_embeddings)

    index.add(sentence_embeddings)
    num_of_IndexedVecs= index.ntotal
    index.nprobe = 4
    print('n total', num_of_IndexedVecs)
    faiss.write_index(index, 'theindex')
    print("trained and saved")
    # 
    #nprobe = 5
    # load and then search
FaissIV()


n total 5143
trained and saved


In [ ]:
# load index 
index = faiss.read_index('theindex')
xq = model.encode(["horror movie"])

k = 10
D, I = index.search(xq, 10)
print(list(I[0]))



[3826, 3859, 1665, 829, 561, 4968, 3292, 4945, 1143, 3239]


In [ ]:
print(df['overview'][3826    ])

While the original parodied slasher flicks like Scream, Keenen Ivory Wayans's sequel to Scary Movie takes comedic aim at haunted house movies. A group of students visit a mansion called "Hell House," and murderous high jinks ensue.


In [ ]:
import pickle
with open('embeddings.pkl', "wb") as fIn:
    pickle.dump(sentence_embeddings, fIn, protocol=pickle.HIGHEST_PROTOCOL)
    print("saved.......")
    

saved.......


In [ ]:
index.ntotal

5

In [ ]:
model = SentenceTransformer('all-MiniLM-L12-v2')
xq = model.encode(['purple'])
D, I = index.search(xq, 2)
print(I)

[[ 0 -1]]


In [ ]:
import faiss 
cells = 2
d = bertModel.dimensions
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, cells)

In [ ]:
index.train(bertModel.sentence_embeddings)


In [ ]:

import pandas as pd
l = [1, 3, 9, 4, 5]
df = pd.DataFrame({'age':    l})


print(df.age.values)
ids = df.age.values
ids = np.arange(bertModel.sentence_embeddings.shape[0])
index.add_with_ids(bertModel.sentence_embeddings, df.age.values)
index.ntotal
# # free add 
# index.add(bertModel.sentence_embeddings)
# index.ntotal

[1 3 9 4 5]


10

In [ ]:
model = SentenceTransformer('all-MiniLM-L12-v2')


In [ ]:
xq = model.encode(['purple'])
D, I = index.search(xq, 2)
print(I)

[[1 3]]


In [ ]:
faiss.write_index(index, 'ag')